/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaecuacionesgauss;

import javax.swing.JOptionPane;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author user
 */
public class MatrizInversa extends javax.swing.JFrame {

    /**
     * Creates new form MatrizInversa
     */
    public MatrizInversa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        jpprimero = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jt1 = new javax.swing.JTextField();
        jt4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jt7 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jt5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jt8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jt3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jt6 = new javax.swing.JTextField();
        jt9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel70 = new javax.swing.JLabel();
        jpsegundo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jtx1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtx4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtx7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtx2 = new javax.swing.JTextField();
        jtx5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtx8 = new javax.swing.JTextField();
        jtx9 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtx3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtx6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jptercero = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jt10 = new javax.swing.JTextField();
        jt11 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jt12 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jt13 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jt14 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jt15 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jt16 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jt17 = new javax.swing.JTextField();
        jt18 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jpcuarto = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jti1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jti2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jti3 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jti6 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jti5 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jti4 = new javax.swing.JTextField();
        jti7 = new javax.swing.JTextField();
        jti8 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jti9 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtdeterminante = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpprimero.setBackground(new java.awt.Color(255, 255, 255));
        jpprimero.setName("jpprimero"); // NOI18N
        jpprimero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("X1");
        jpprimero.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jt1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpprimero.add(jt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 80, -1));

        jt4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpprimero.add(jt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 80, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setText("X4");
        jpprimero.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jt7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpprimero.add(jt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 80, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setText("X7");
        jpprimero.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        jt2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpprimero.add(jt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 80, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setText("X2");
        jpprimero.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setText("X5");
        jpprimero.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jt5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpprimero.add(jt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 80, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel6.setText("X8");
        jpprimero.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jt8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpprimero.add(jt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 80, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel7.setText("MATRIZ ORIGINAL");
        jpprimero.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jt3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpprimero.add(jt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 80, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel8.setText("X6");
        jpprimero.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jt6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpprimero.add(jt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 80, -1));

        jt9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpprimero.add(jt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 80, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel9.setText("X9");
        jpprimero.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel10.setText("X3");
        jpprimero.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Avanzar");
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpprimero.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 100, 40));

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/house.png"))); // NOI18N
        jLabel70.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel70MouseClicked(evt);
            }
        });
        jpprimero.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        rSPanelsSlider1.add(jpprimero, "card2");

        jpsegundo.setBackground(new java.awt.Color(255, 255, 255));
        jpsegundo.setName("jpsegundo"); // NOI18N
        jpsegundo.setPreferredSize(new java.awt.Dimension(500, 500));
        jpsegundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel12.setText("MATRIZ ADJUNTA");
        jpsegundo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jtx1.setEditable(false);
        jtx1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(jtx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 70, -1));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel13.setText("X1");
        jpsegundo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jtx4.setEditable(false);
        jtx4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(jtx4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 70, -1));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel14.setText("X4");
        jpsegundo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jtx7.setEditable(false);
        jtx7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(jtx7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 70, -1));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel15.setText("X7");
        jpsegundo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        jtx2.setEditable(false);
        jtx2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(jtx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 70, -1));

        jtx5.setEditable(false);
        jtx5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(jtx5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 70, -1));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel16.setText("X5");
        jpsegundo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel17.setText("X2");
        jpsegundo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jtx8.setEditable(false);
        jtx8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(jtx8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 70, -1));

        jtx9.setEditable(false);
        jtx9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(jtx9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 70, -1));

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel18.setText("X8");
        jpsegundo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jtx3.setEditable(false);
        jtx3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jtx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx3ActionPerformed(evt);
            }
        });
        jpsegundo.add(jtx3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 70, -1));

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel19.setText("X6");
        jpsegundo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel20.setText("X3");
        jpsegundo.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jtx6.setEditable(false);
        jtx6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(jtx6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 70, -1));

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel21.setText("X9");
        jpsegundo.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Avanzar");
        jButton2.setBorder(null);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jpsegundo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 100, 40));

        rSPanelsSlider1.add(jpsegundo, "card3");

        jptercero.setBackground(new java.awt.Color(255, 255, 255));
        jptercero.setName("jptercero"); // NOI18N
        jptercero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel22.setText("X1");
        jptercero.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jt10.setEditable(false);
        jt10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(jt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 100, -1));

        jt11.setEditable(false);
        jt11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(jt11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 100, -1));

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel23.setText("X4");
        jptercero.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jt12.setEditable(false);
        jt12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(jt12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 100, -1));

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel24.setText("X7");
        jptercero.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        jt13.setEditable(false);
        jt13.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(jt13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 100, -1));

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel25.setText("X2");
        jptercero.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel26.setText("X5");
        jptercero.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jt14.setEditable(false);
        jt14.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(jt14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 100, -1));

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel27.setText("X8");
        jptercero.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jt15.setEditable(false);
        jt15.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(jt15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 100, -1));

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel28.setText("MATRIZ TRANSPUESTA(ADJ)");
        jptercero.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jt16.setEditable(false);
        jt16.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(jt16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 100, -1));

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel29.setText("X6");
        jptercero.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jt17.setEditable(false);
        jt17.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(jt17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 100, -1));

        jt18.setEditable(false);
        jt18.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(jt18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 100, -1));

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel30.setText("X9");
        jptercero.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel31.setText("X3");
        jptercero.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Avanzar");
        jButton3.setBorder(null);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jptercero.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 100, 40));

        rSPanelsSlider1.add(jptercero, "card2");

        jpcuarto.setBackground(new java.awt.Color(255, 255, 255));
        jpcuarto.setName("jpcuarto"); // NOI18N
        jpcuarto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel32.setText("MATRIZ INVERSA");
        jpcuarto.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jti1.setEditable(false);
        jti1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(jti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, 40));

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel33.setText("X1");
        jpcuarto.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jti2.setEditable(false);
        jti2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(jti2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 120, 40));

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel34.setText("X2");
        jpcuarto.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jti3.setEditable(false);
        jti3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(jti3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 120, 40));

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel35.setText("X3");
        jpcuarto.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        jLabel36.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel36.setText("X6");
        jpcuarto.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

        jti6.setEditable(false);
        jti6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(jti6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 120, 40));

        jLabel37.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel37.setText("X5");
        jpcuarto.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        jti5.setEditable(false);
        jti5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(jti5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 120, 40));

        jLabel38.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel38.setText("X4");
        jpcuarto.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jti4.setEditable(false);
        jti4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(jti4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 120, 40));

        jti7.setEditable(false);
        jti7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(jti7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 120, 40));

        jti8.setEditable(false);
        jti8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(jti8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 120, 40));

        jLabel39.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel39.setText("X7");
        jpcuarto.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel40.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel40.setText("X8");
        jpcuarto.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        jLabel41.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel41.setText("X9");
        jpcuarto.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, -1));

        jti9.setEditable(false);
        jti9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(jti9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 120, 40));

        jButton5.setBackground(new java.awt.Color(0, 102, 204));
        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Volver");
        jButton5.setBorder(null);
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jpcuarto.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 100, 40));

        rSPanelsSlider1.add(jpcuarto, "card5");

        jPanel1.add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 440));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 440));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel11.setText("DETERMINANTE: ");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jtdeterminante.setEditable(false);
        jtdeterminante.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jPanel4.add(jtdeterminante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 140, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 800, 110));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     boolean r=true;
        try{
          
       Inversa.cargarMatriz(jt1, jt4, jt7, jt2, jt5, jt8, jt3, jt6, jt9);
   
      if( Inversa.encontrarDeterminante()=="0"){
      
          r=false;
          
      }else {
      
      jtdeterminante.setText(Inversa.encontrarDeterminante());
      }
       
      
     }catch(Exception e){
     JOptionPane.showMessageDialog(null, " Porfavor ingrese Los datos Correctos y vuelva a intentarlo");
      r=false;
     }
     if(r==true){
      Inversa.matrizAdjunta(jtx1, jtx4, jtx7, jtx2, jtx5, jtx8, jtx3, jtx6, jtx9);
     rSPanelsSlider1.setPanelSlider(20,jpsegundo, RSPanelsSlider.DIRECT.RIGHT);
     
     }
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Inversa.matrizAdjunta(jt10, jt13, jt16, jt11, jt14, jt17, jt12, jt15, jt18);
     rSPanelsSlider1.setPanelSlider(20,jptercero, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Inversa.matrizInversa3x3(jti1, jti2, jti3, jti4, jti5, jti6, jti7, jti8, jti9);
       rSPanelsSlider1.setPanelSlider(20,jpcuarto, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jt1.setText("");
        jt2.setText("");
        jt3.setText("");
        jt4.setText("");
        jt5.setText("");
        jt6.setText("");
        jt7.setText("");
        jt8.setText("");
        jt9.setText("");
        jtdeterminante.setText("");
        rSPanelsSlider1.setPanelSlider(20,jpprimero, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel70MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel70MouseClicked
        MenuInversas a = new MenuInversas();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel70MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatrizInversa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatrizInversa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatrizInversa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatrizInversa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatrizInversa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpcuarto;
    private javax.swing.JPanel jpprimero;
    private javax.swing.JPanel jpsegundo;
    private javax.swing.JPanel jptercero;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt10;
    private javax.swing.JTextField jt11;
    private javax.swing.JTextField jt12;
    private javax.swing.JTextField jt13;
    private javax.swing.JTextField jt14;
    private javax.swing.JTextField jt15;
    private javax.swing.JTextField jt16;
    private javax.swing.JTextField jt17;
    private javax.swing.JTextField jt18;
    private javax.swing.JTextField jt2;
    private javax.swing.JTextField jt3;
    private javax.swing.JTextField jt4;
    private javax.swing.JTextField jt5;
    private javax.swing.JTextField jt6;
    private javax.swing.JTextField jt7;
    private javax.swing.JTextField jt8;
    private javax.swing.JTextField jt9;
    private javax.swing.JTextField jtdeterminante;
    private javax.swing.JTextField jti1;
    private javax.swing.JTextField jti2;
    private javax.swing.JTextField jti3;
    private javax.swing.JTextField jti4;
    private javax.swing.JTextField jti5;
    private javax.swing.JTextField jti6;
    private javax.swing.JTextField jti7;
    private javax.swing.JTextField jti8;
    private javax.swing.JTextField jti9;
    private javax.swing.JTextField jtx1;
    private javax.swing.JTextField jtx2;
    private javax.swing.JTextField jtx3;
    private javax.swing.JTextField jtx4;
    private javax.swing.JTextField jtx5;
    private javax.swing.JTextField jtx6;
    private javax.swing.JTextField jtx7;
    private javax.swing.JTextField jtx8;
    private javax.swing.JTextField jtx9;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    // End of variables declaration//GEN-END:variables
}
