/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaecuacionesgauss;

import javax.swing.JOptionPane;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author user
 */
public class MatrizInversa4x4 extends javax.swing.JFrame {

    /**
     * Creates new form MatrizInversa4x4
     */
    public MatrizInversa4x4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        JPS4x4 = new rojerusan.RSPanelsSlider();
        jpprimero = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jtt1 = new javax.swing.JTextField();
        jtt2 = new javax.swing.JTextField();
        jtt3 = new javax.swing.JTextField();
        jtt4 = new javax.swing.JTextField();
        jtt5 = new javax.swing.JTextField();
        jtt6 = new javax.swing.JTextField();
        jtt7 = new javax.swing.JTextField();
        jtt8 = new javax.swing.JTextField();
        jtt9 = new javax.swing.JTextField();
        jtt10 = new javax.swing.JTextField();
        jtt11 = new javax.swing.JTextField();
        jtt12 = new javax.swing.JTextField();
        jtt13 = new javax.swing.JTextField();
        jtt14 = new javax.swing.JTextField();
        jtt15 = new javax.swing.JTextField();
        jtt16 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jpsegundo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        ma1 = new javax.swing.JTextField();
        ma2 = new javax.swing.JTextField();
        ma3 = new javax.swing.JTextField();
        ma4 = new javax.swing.JTextField();
        ma5 = new javax.swing.JTextField();
        ma6 = new javax.swing.JTextField();
        ma7 = new javax.swing.JTextField();
        ma8 = new javax.swing.JTextField();
        ma9 = new javax.swing.JTextField();
        ma10 = new javax.swing.JTextField();
        ma11 = new javax.swing.JTextField();
        ma12 = new javax.swing.JTextField();
        ma13 = new javax.swing.JTextField();
        ma14 = new javax.swing.JTextField();
        ma15 = new javax.swing.JTextField();
        ma16 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jptercero = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        mt1 = new javax.swing.JTextField();
        mt5 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        mt9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        mt2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        mt6 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        mt10 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        mt3 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        mt7 = new javax.swing.JTextField();
        mt11 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        mt4 = new javax.swing.JTextField();
        mt8 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        mt12 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        mt13 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        mt14 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        mt15 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        mt16 = new javax.swing.JTextField();
        jpcuarto = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        mi1 = new javax.swing.JTextField();
        mi2 = new javax.swing.JTextField();
        mi3 = new javax.swing.JTextField();
        mi4 = new javax.swing.JTextField();
        mi5 = new javax.swing.JTextField();
        mi6 = new javax.swing.JTextField();
        mi7 = new javax.swing.JTextField();
        mi8 = new javax.swing.JTextField();
        mi9 = new javax.swing.JTextField();
        mi10 = new javax.swing.JTextField();
        mi11 = new javax.swing.JTextField();
        mi12 = new javax.swing.JTextField();
        mi13 = new javax.swing.JTextField();
        mi14 = new javax.swing.JTextField();
        mi15 = new javax.swing.JTextField();
        mi16 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jttdeterminante = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpprimero.setBackground(new java.awt.Color(255, 255, 255));
        jpprimero.setName("jpprimero"); // NOI18N
        jpprimero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("X1");
        jpprimero.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setText("X5");
        jpprimero.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setText("X9");
        jpprimero.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setText("X2");
        jpprimero.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setText("X6");
        jpprimero.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel6.setText("X10");
        jpprimero.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel7.setText("MATRIZ ORIGINAL");
        jpprimero.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel8.setText("X7");
        jpprimero.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel9.setText("X11");
        jpprimero.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel10.setText("X3");
        jpprimero.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Avanzar");
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpprimero.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 100, 40));

        jLabel42.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel42.setText("X4");
        jpprimero.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, -1, -1));

        jLabel43.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel43.setText("X8");
        jpprimero.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        jLabel44.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel44.setText("X12");
        jpprimero.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        jLabel54.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel54.setText("X13");
        jpprimero.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jLabel55.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel55.setText("X14");
        jpprimero.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        jLabel56.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel56.setText("X15");
        jpprimero.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        jLabel57.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel57.setText("X16");
        jpprimero.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        jtt1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpprimero.add(jtt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 80, -1));

        jtt2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpprimero.add(jtt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 80, -1));

        jtt3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jtt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtt3ActionPerformed(evt);
            }
        });
        jpprimero.add(jtt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 80, -1));

        jtt4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jtt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtt4ActionPerformed(evt);
            }
        });
        jpprimero.add(jtt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 80, -1));

        jtt5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jtt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtt5ActionPerformed(evt);
            }
        });
        jpprimero.add(jtt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 80, -1));

        jtt6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jtt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtt6ActionPerformed(evt);
            }
        });
        jpprimero.add(jtt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 80, -1));

        jtt7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jtt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtt7ActionPerformed(evt);
            }
        });
        jpprimero.add(jtt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 80, -1));

        jtt8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jtt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtt8ActionPerformed(evt);
            }
        });
        jpprimero.add(jtt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 80, -1));

        jtt9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jtt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtt9ActionPerformed(evt);
            }
        });
        jpprimero.add(jtt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 80, -1));

        jtt10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jtt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtt10ActionPerformed(evt);
            }
        });
        jpprimero.add(jtt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 80, -1));

        jtt11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jtt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtt11ActionPerformed(evt);
            }
        });
        jpprimero.add(jtt11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 80, -1));

        jtt12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jtt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtt12ActionPerformed(evt);
            }
        });
        jpprimero.add(jtt12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 80, -1));

        jtt13.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jtt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtt13ActionPerformed(evt);
            }
        });
        jpprimero.add(jtt13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 80, -1));

        jtt14.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jtt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtt14ActionPerformed(evt);
            }
        });
        jpprimero.add(jtt14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 80, -1));

        jtt15.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jtt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtt15ActionPerformed(evt);
            }
        });
        jpprimero.add(jtt15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 80, -1));

        jtt16.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jtt16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtt16ActionPerformed(evt);
            }
        });
        jpprimero.add(jtt16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 80, -1));

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/house.png"))); // NOI18N
        jLabel70.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel70MouseClicked(evt);
            }
        });
        jpprimero.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        JPS4x4.add(jpprimero, "card2");

        jpsegundo.setBackground(new java.awt.Color(255, 255, 255));
        jpsegundo.setName("jpsegundo"); // NOI18N
        jpsegundo.setPreferredSize(new java.awt.Dimension(500, 500));
        jpsegundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel12.setText("MATRIZ ADJUNTA");
        jpsegundo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        ma1.setEditable(false);
        ma1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(ma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 70, -1));

        ma2.setEditable(false);
        ma2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(ma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 70, -1));

        ma3.setEditable(false);
        ma3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        ma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ma3ActionPerformed(evt);
            }
        });
        jpsegundo.add(ma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 70, -1));

        ma4.setEditable(false);
        ma4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        ma4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ma4ActionPerformed(evt);
            }
        });
        jpsegundo.add(ma4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 70, -1));

        ma5.setEditable(false);
        ma5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(ma5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 70, -1));

        ma6.setEditable(false);
        ma6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(ma6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 70, -1));

        ma7.setEditable(false);
        ma7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(ma7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 70, -1));

        ma8.setEditable(false);
        ma8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(ma8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 70, -1));

        ma9.setEditable(false);
        ma9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(ma9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 70, -1));

        ma10.setEditable(false);
        ma10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(ma10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 70, -1));

        ma11.setEditable(false);
        ma11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(ma11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 70, -1));

        ma12.setEditable(false);
        ma12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(ma12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 70, -1));

        ma13.setEditable(false);
        ma13.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(ma13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 70, -1));

        ma14.setEditable(false);
        ma14.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(ma14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 70, -1));

        ma15.setEditable(false);
        ma15.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(ma15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 70, -1));

        ma16.setEditable(false);
        ma16.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpsegundo.add(ma16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 70, -1));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel13.setText("X1");
        jpsegundo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel14.setText("X5");
        jpsegundo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel15.setText("X9");
        jpsegundo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel16.setText("X6");
        jpsegundo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel17.setText("X2");
        jpsegundo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel18.setText("X10");
        jpsegundo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel19.setText("X7");
        jpsegundo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel20.setText("X3");
        jpsegundo.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel21.setText("X11");
        jpsegundo.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Avanzar");
        jButton2.setBorder(null);
        jButton2.setOpaque(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jpsegundo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 100, 40));

        jLabel45.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel45.setText("X4");
        jpsegundo.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        jLabel46.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel46.setText("X8");
        jpsegundo.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, -1, -1));

        jLabel47.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel47.setText("X12");
        jpsegundo.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));

        jLabel58.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel58.setText("X13");
        jpsegundo.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        jLabel59.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel59.setText("X14");
        jpsegundo.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        jLabel60.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel60.setText("X15");
        jpsegundo.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        jLabel61.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel61.setText("X16");
        jpsegundo.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, -1));

        JPS4x4.add(jpsegundo, "card3");

        jptercero.setBackground(new java.awt.Color(255, 255, 255));
        jptercero.setName("jptercero"); // NOI18N
        jptercero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel22.setText("X1");
        jptercero.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        mt1.setEditable(false);
        mt1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, -1));

        mt5.setEditable(false);
        mt5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 100, -1));

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel23.setText("X5");
        jptercero.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        mt9.setEditable(false);
        mt9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 100, -1));

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel24.setText("X9");
        jptercero.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        mt2.setEditable(false);
        mt2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 100, -1));

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel25.setText("X2");
        jptercero.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel26.setText("X6");
        jptercero.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        mt6.setEditable(false);
        mt6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 100, -1));

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel27.setText("X10");
        jptercero.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        mt10.setEditable(false);
        mt10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 100, -1));

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel28.setText("MATRIZ TRANSPUESTA(ADJ)");
        jptercero.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        mt3.setEditable(false);
        mt3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 100, -1));

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel29.setText("X7");
        jptercero.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        mt7.setEditable(false);
        mt7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 100, -1));

        mt11.setEditable(false);
        mt11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 100, -1));

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel30.setText("X11");
        jptercero.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel31.setText("X3");
        jptercero.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Avanzar");
        jButton3.setBorder(null);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jptercero.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 100, 40));

        jLabel48.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel48.setText("X4");
        jptercero.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, -1));

        mt4.setEditable(false);
        mt4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 100, -1));

        mt8.setEditable(false);
        mt8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 100, -1));

        jLabel49.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel49.setText("X8");
        jptercero.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, -1));

        mt12.setEditable(false);
        mt12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 100, -1));

        jLabel50.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel50.setText("X12");
        jptercero.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, -1));

        jLabel62.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel62.setText("X16");
        jptercero.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, -1));

        mt13.setEditable(false);
        mt13.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 100, -1));

        jLabel63.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel63.setText("X13");
        jptercero.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        mt14.setEditable(false);
        mt14.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 100, -1));

        jLabel64.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel64.setText("X14");
        jptercero.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        mt15.setEditable(false);
        mt15.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 100, -1));

        jLabel65.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel65.setText("X15");
        jptercero.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        mt16.setEditable(false);
        mt16.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jptercero.add(mt16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 100, -1));

        JPS4x4.add(jptercero, "card2");

        jpcuarto.setBackground(new java.awt.Color(255, 255, 255));
        jpcuarto.setName("jpcuarto"); // NOI18N
        jpcuarto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel32.setText("MATRIZ INVERSA");
        jpcuarto.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        mi1.setEditable(false);
        mi1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 40));

        mi2.setEditable(false);
        mi2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 120, 40));

        mi3.setEditable(false);
        mi3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 120, 40));

        mi4.setEditable(false);
        mi4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 120, 40));

        mi5.setEditable(false);
        mi5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, 40));

        mi6.setEditable(false);
        mi6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 120, 40));

        mi7.setEditable(false);
        mi7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 120, 40));

        mi8.setEditable(false);
        mi8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 120, 40));

        mi9.setEditable(false);
        mi9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, 40));

        mi10.setEditable(false);
        mi10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 120, 40));

        mi11.setEditable(false);
        mi11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 120, 40));

        mi12.setEditable(false);
        mi12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 120, 40));

        mi13.setEditable(false);
        mi13.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 120, 40));

        mi14.setEditable(false);
        mi14.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 120, 40));

        mi15.setEditable(false);
        mi15.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 120, 40));

        mi16.setEditable(false);
        mi16.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jpcuarto.add(mi16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 120, 40));

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel33.setText("X1");
        jpcuarto.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel34.setText("X2");
        jpcuarto.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel35.setText("X3");
        jpcuarto.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        jLabel36.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel36.setText("X7");
        jpcuarto.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        jLabel37.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel37.setText("X6");
        jpcuarto.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        jLabel38.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel38.setText("X5");
        jpcuarto.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jLabel39.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel39.setText("X9");
        jpcuarto.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jLabel40.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel40.setText("X10");
        jpcuarto.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jLabel41.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel41.setText("X11");
        jpcuarto.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 102, 204));
        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Volver");
        jButton5.setBorder(null);
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jpcuarto.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 100, 40));

        jLabel51.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel51.setText("X4");
        jpcuarto.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, -1, -1));

        jLabel52.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel52.setText("X8");
        jpcuarto.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, -1, -1));

        jLabel53.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel53.setText("X12");
        jpcuarto.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, -1));

        jLabel66.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel66.setText("X13");
        jpcuarto.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        jLabel67.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel67.setText("X14");
        jpcuarto.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        jLabel68.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel68.setText("X15");
        jpcuarto.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        jLabel69.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel69.setText("X16");
        jpcuarto.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, -1, -1));

        JPS4x4.add(jpcuarto, "card5");

        jPanel1.add(JPS4x4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 440));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 440));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel11.setText("DETERMINANTE: ");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jttdeterminante.setEditable(false);
        jttdeterminante.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jPanel4.add(jttdeterminante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 140, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 800, 110));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
     

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ma3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ma3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    Inversa.matrizInversa4x4(mi1,mi5,mi9,mi13,mi2,mi6,mi10,mi14,mi3,mi7,mi11,mi15,mi4,mi8,mi12,mi16);
     JPS4x4.setPanelSlider(20,jpcuarto, RSPanelsSlider.DIRECT.RIGHT);

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jtt1.setText("");
        jtt2.setText("");
        jtt3.setText("");
        jtt4.setText("");
        jtt5.setText("");
        jtt6.setText("");
        jtt7.setText("");
        jtt8.setText("");
        jtt9.setText("");
        jtt10.setText("");
        jtt11.setText("");
        jtt12.setText("");
        jtt13.setText("");
        jtt14.setText("");
        jtt15.setText("");
        jtt16.setText("");
        jttdeterminante.setText("");
        JPS4x4.setPanelSlider(20,jpprimero, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ma4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ma4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ma4ActionPerformed

    private void jtt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtt3ActionPerformed

    private void jtt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtt4ActionPerformed

    private void jtt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtt5ActionPerformed

    private void jtt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtt6ActionPerformed

    private void jtt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtt7ActionPerformed

    private void jtt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtt8ActionPerformed

    private void jtt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtt9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtt9ActionPerformed

    private void jtt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtt10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtt10ActionPerformed

    private void jtt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtt11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtt11ActionPerformed

    private void jtt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtt12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtt12ActionPerformed

    private void jtt13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtt13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtt13ActionPerformed

    private void jtt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtt14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtt14ActionPerformed

    private void jtt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtt15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtt15ActionPerformed

    private void jtt16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtt16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtt16ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
             boolean r=true;
        try{
          
       Inversa.cargarMatriz4x4(jtt1, jtt2, jtt3, jtt4, jtt5, jtt6, jtt7, jtt8, jtt9, jtt10, jtt11, jtt12, jtt13, jtt14, jtt15, jtt16);
   
      if( Inversa.Determinante4x4()=="0"){
      
          r=false;
          
      }else {
      
      jttdeterminante.setText(Inversa.Determinante4x4());
      }
       
      
     }catch(Exception e){
     JOptionPane.showMessageDialog(null, " Porfavor ingrese Los datos Correctos y vuelva a intentarlo");
      r=false;
     }
     if(r==true){
      Inversa.matrizAdjunta4x4(ma1, ma2, ma3, ma4, ma5, ma6, ma7, ma8, ma9, ma10, ma11, ma12, ma13, ma14, ma15, ma16);
     JPS4x4.setPanelSlider(20,jpsegundo, RSPanelsSlider.DIRECT.RIGHT);
     
     }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Inversa.matrizAdjunta4x4(mt1,mt5,mt9,mt13,mt2,mt6,mt10,mt14,mt3,mt7,mt11,mt15,mt4,mt8,mt12,mt16);
        JPS4x4.setPanelSlider(20,jptercero, RSPanelsSlider.DIRECT.RIGHT);
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel70MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel70MouseClicked
       MenuInversas a = new MenuInversas();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel70MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatrizInversa4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatrizInversa4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatrizInversa4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatrizInversa4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatrizInversa4x4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSPanelsSlider JPS4x4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpcuarto;
    private javax.swing.JPanel jpprimero;
    private javax.swing.JPanel jpsegundo;
    private javax.swing.JPanel jptercero;
    private javax.swing.JTextField jtt1;
    private javax.swing.JTextField jtt10;
    private javax.swing.JTextField jtt11;
    private javax.swing.JTextField jtt12;
    private javax.swing.JTextField jtt13;
    private javax.swing.JTextField jtt14;
    private javax.swing.JTextField jtt15;
    private javax.swing.JTextField jtt16;
    private javax.swing.JTextField jtt2;
    private javax.swing.JTextField jtt3;
    private javax.swing.JTextField jtt4;
    private javax.swing.JTextField jtt5;
    private javax.swing.JTextField jtt6;
    private javax.swing.JTextField jtt7;
    private javax.swing.JTextField jtt8;
    private javax.swing.JTextField jtt9;
    private javax.swing.JTextField jttdeterminante;
    private javax.swing.JTextField ma1;
    private javax.swing.JTextField ma10;
    private javax.swing.JTextField ma11;
    private javax.swing.JTextField ma12;
    private javax.swing.JTextField ma13;
    private javax.swing.JTextField ma14;
    private javax.swing.JTextField ma15;
    private javax.swing.JTextField ma16;
    private javax.swing.JTextField ma2;
    private javax.swing.JTextField ma3;
    private javax.swing.JTextField ma4;
    private javax.swing.JTextField ma5;
    private javax.swing.JTextField ma6;
    private javax.swing.JTextField ma7;
    private javax.swing.JTextField ma8;
    private javax.swing.JTextField ma9;
    private javax.swing.JTextField mi1;
    private javax.swing.JTextField mi10;
    private javax.swing.JTextField mi11;
    private javax.swing.JTextField mi12;
    private javax.swing.JTextField mi13;
    private javax.swing.JTextField mi14;
    private javax.swing.JTextField mi15;
    private javax.swing.JTextField mi16;
    private javax.swing.JTextField mi2;
    private javax.swing.JTextField mi3;
    private javax.swing.JTextField mi4;
    private javax.swing.JTextField mi5;
    private javax.swing.JTextField mi6;
    private javax.swing.JTextField mi7;
    private javax.swing.JTextField mi8;
    private javax.swing.JTextField mi9;
    private javax.swing.JTextField mt1;
    private javax.swing.JTextField mt10;
    private javax.swing.JTextField mt11;
    private javax.swing.JTextField mt12;
    private javax.swing.JTextField mt13;
    private javax.swing.JTextField mt14;
    private javax.swing.JTextField mt15;
    private javax.swing.JTextField mt16;
    private javax.swing.JTextField mt2;
    private javax.swing.JTextField mt3;
    private javax.swing.JTextField mt4;
    private javax.swing.JTextField mt5;
    private javax.swing.JTextField mt6;
    private javax.swing.JTextField mt7;
    private javax.swing.JTextField mt8;
    private javax.swing.JTextField mt9;
    // End of variables declaration//GEN-END:variables
}
