/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaecuacionesgauss;

import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author UNIVALLE
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    Hilo1 comprobar;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);

        //ecuacion1
        e1.setVisible(false);
        var1.setVisible(false);
        op1.setVisible(false);
        e2.setVisible(false);
        var5.setVisible(false);
        op2.setVisible(false);
        e3.setVisible(false);
        var9.setVisible(false);
        op3.setVisible(false);
        e4.setVisible(false);
        var13.setVisible(false);
        op4.setVisible(false);
        e5.setVisible(false);
        //ecuacion2
        e6.setVisible(false);
        var2.setVisible(false);
        op5.setVisible(false);
        e7.setVisible(false);
        var6.setVisible(false);
        op6.setVisible(false);
        e8.setVisible(false);
        var10.setVisible(false);
        op7.setVisible(false);
        e9.setVisible(false);
        var14.setVisible(false);
        op8.setVisible(false);
        e10.setVisible(false);
        //ecuacion3
        e11.setVisible(false);
        var4.setVisible(false);
        op9.setVisible(false);
        e12.setVisible(false);
        var8.setVisible(false);
        op10.setVisible(false);
        e13.setVisible(false);
        var12.setVisible(false);
        op11.setVisible(false);
        e14.setVisible(false);
        var16.setVisible(false);
        op12.setVisible(false);
        e15.setVisible(false);
        //ecuacion4
        e16.setVisible(false);
        var3.setVisible(false);
        op13.setVisible(false);
        e17.setVisible(false);
        var7.setVisible(false);
        op14.setVisible(false);
        e18.setVisible(false);
        var11.setVisible(false);
        op15.setVisible(false);
        e19.setVisible(false);
        var15.setVisible(false);
        op16.setVisible(false);
        e20.setVisible(false);
        comprobar = new Hilo1(camb2, camb4, camb6, camb8, var1, var2, var3, var4, var5, var6, var7, var8, var9, var10, var11, var12, var13, var14, var15, var16);

    }

    public void evento(KeyEvent evt, JTextField e) {
        boolean r = true;

        if ((int) evt.getKeyChar() == KeyEvent.VK_TAB && r) {
            r = false;
            e.setText("");
        } else if (((int) evt.getKeyChar()) == 8) {

        } else if (((int) evt.getKeyChar()) == 47 || ((int) evt.getKeyChar()) == 45 || ((int) evt.getKeyChar()) == 127) {

        } else if (((int) evt.getKeyChar()) < 48 || ((int) evt.getKeyChar()) > 57) {

            JOptionPane.showMessageDialog(null, "SOLO PUEDE INGRESAR NUMEROS", "ERROR AL INGRESAR DATOS", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tamano = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        e1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        camb9 = new javax.swing.JLabel();
        op1 = new javax.swing.JLabel();
        e2 = new javax.swing.JTextField();
        var5 = new javax.swing.JLabel();
        op2 = new javax.swing.JLabel();
        e3 = new javax.swing.JTextField();
        var9 = new javax.swing.JLabel();
        op3 = new javax.swing.JLabel();
        e4 = new javax.swing.JTextField();
        var13 = new javax.swing.JLabel();
        op4 = new javax.swing.JLabel();
        e5 = new javax.swing.JTextField();
        e6 = new javax.swing.JTextField();
        var2 = new javax.swing.JLabel();
        op5 = new javax.swing.JLabel();
        e7 = new javax.swing.JTextField();
        var6 = new javax.swing.JLabel();
        op6 = new javax.swing.JLabel();
        e8 = new javax.swing.JTextField();
        var10 = new javax.swing.JLabel();
        op7 = new javax.swing.JLabel();
        e9 = new javax.swing.JTextField();
        var14 = new javax.swing.JLabel();
        op8 = new javax.swing.JLabel();
        e10 = new javax.swing.JTextField();
        e11 = new javax.swing.JTextField();
        var3 = new javax.swing.JLabel();
        op9 = new javax.swing.JLabel();
        e12 = new javax.swing.JTextField();
        var7 = new javax.swing.JLabel();
        op10 = new javax.swing.JLabel();
        e13 = new javax.swing.JTextField();
        var11 = new javax.swing.JLabel();
        op11 = new javax.swing.JLabel();
        e14 = new javax.swing.JTextField();
        var15 = new javax.swing.JLabel();
        op12 = new javax.swing.JLabel();
        e15 = new javax.swing.JTextField();
        e16 = new javax.swing.JTextField();
        var4 = new javax.swing.JLabel();
        op13 = new javax.swing.JLabel();
        e17 = new javax.swing.JTextField();
        var8 = new javax.swing.JLabel();
        op14 = new javax.swing.JLabel();
        e18 = new javax.swing.JTextField();
        var12 = new javax.swing.JLabel();
        op15 = new javax.swing.JLabel();
        e19 = new javax.swing.JTextField();
        var16 = new javax.swing.JLabel();
        op16 = new javax.swing.JLabel();
        e20 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumen = new javax.swing.JTextArea();
        camb2 = new javax.swing.JTextField();
        var1 = new javax.swing.JLabel();
        camb3 = new javax.swing.JLabel();
        camb4 = new javax.swing.JTextField();
        camb5 = new javax.swing.JLabel();
        camb6 = new javax.swing.JTextField();
        camb7 = new javax.swing.JLabel();
        camb8 = new javax.swing.JTextField();
        camb1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        tamano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "       ", "3x3", "4x4" }));
        tamano.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 2, 0));
        tamano.setOpaque(false);
        tamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanoActionPerformed(evt);
            }
        });
        jPanel1.add(tamano);
        tamano.setBounds(340, 100, 120, 30);

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Tamaño");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 80, 150, 23);
        jLabel2.getAccessibleContext().setAccessibleName("Tamaño Matriz");

        e1.setBackground(new java.awt.Color(0, 0, 0));
        e1.setColumns(5);
        e1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e1.setForeground(new java.awt.Color(255, 255, 255));
        e1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e1.setText("0");
        e1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e1.setCaretColor(new java.awt.Color(255, 255, 255));
        e1.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e1.setOpaque(false);
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        e1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e1KeyTyped(evt);
            }
        });
        jPanel1.add(e1);
        e1.setBounds(120, 150, 70, 30);
        e1.setVisible(false);

        jButton1.setText("RESOLVER");
        jButton1.setVisible(false);
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setBorderPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 350, 130, 30);

        camb9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        camb9.setForeground(new java.awt.Color(255, 255, 255));
        camb9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        camb9.setText("}");
        jPanel1.add(camb9);
        camb9.setBounds(250, 60, 30, 30);
        camb9.getAccessibleContext().setAccessibleName("");
        camb9.setVisible(false);

        op1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op1.setForeground(new java.awt.Color(255, 255, 255));
        op1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op1.setText("+");
        jPanel1.add(op1);
        op1.setBounds(220, 150, 15, 30);
        op1.setVisible(false);

        e2.setBackground(new java.awt.Color(0, 0, 0));
        e2.setColumns(5);
        e2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e2.setForeground(new java.awt.Color(255, 255, 255));
        e2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e2.setText("0");
        e2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e2.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e2.setOpaque(false);
        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });
        e2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e2KeyTyped(evt);
            }
        });
        jPanel1.add(e2);
        e2.setBounds(240, 150, 70, 30);
        e2.setVisible(false);

        var5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var5.setForeground(new java.awt.Color(255, 255, 255));
        var5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var5.setText("x2");
        jPanel1.add(var5);
        var5.setBounds(310, 150, 30, 30);
        var5.setVisible(false);

        op2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op2.setForeground(new java.awt.Color(255, 255, 255));
        op2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op2.setText("+");
        jPanel1.add(op2);
        op2.setBounds(340, 150, 15, 30);
        op2.setVisible(false);

        e3.setBackground(new java.awt.Color(0, 0, 0));
        e3.setColumns(5);
        e3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e3.setForeground(new java.awt.Color(255, 255, 255));
        e3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e3.setText("0");
        e3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e3.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e3.setOpaque(false);
        e3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e3ActionPerformed(evt);
            }
        });
        e3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e3KeyTyped(evt);
            }
        });
        jPanel1.add(e3);
        e3.setBounds(360, 150, 70, 30);
        e3.setVisible(false);

        var9.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var9.setForeground(new java.awt.Color(255, 255, 255));
        var9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var9.setText("x3");
        jPanel1.add(var9);
        var9.setBounds(430, 150, 30, 30);

        op3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op3.setForeground(new java.awt.Color(255, 255, 255));
        op3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op3.setText("+");
        jPanel1.add(op3);
        op3.setBounds(460, 150, 15, 30);
        op3.setVisible(false);

        e4.setBackground(new java.awt.Color(0, 0, 0));
        e4.setColumns(5);
        e4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e4.setForeground(new java.awt.Color(255, 255, 255));
        e4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e4.setText("0");
        e4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e4.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e4.setOpaque(false);
        e4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e4KeyTyped(evt);
            }
        });
        jPanel1.add(e4);
        e4.setBounds(480, 150, 70, 30);
        e4.setVisible(false);

        var13.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var13.setForeground(new java.awt.Color(255, 255, 255));
        var13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var13.setText("x4");
        jPanel1.add(var13);
        var13.setBounds(550, 150, 30, 30);
        var13.setVisible(false);

        op4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op4.setForeground(new java.awt.Color(255, 255, 255));
        op4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op4.setText("=");
        jPanel1.add(op4);
        op4.setBounds(580, 150, 15, 30);
        op4.setVisible(false);

        e5.setBackground(new java.awt.Color(0, 0, 0));
        e5.setColumns(5);
        e5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e5.setForeground(new java.awt.Color(255, 255, 255));
        e5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e5.setText("0");
        e5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e5.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e5.setOpaque(false);
        e5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e5KeyTyped(evt);
            }
        });
        jPanel1.add(e5);
        e5.setBounds(600, 150, 70, 30);
        e5.setVisible(false);

        e6.setBackground(new java.awt.Color(0, 0, 0));
        e6.setColumns(5);
        e6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e6.setForeground(new java.awt.Color(255, 255, 255));
        e6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e6.setText("0");
        e6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e6.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e6.setOpaque(false);
        e6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e6ActionPerformed(evt);
            }
        });
        e6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e6KeyTyped(evt);
            }
        });
        jPanel1.add(e6);
        e6.setBounds(120, 200, 70, 30);
        e6.setVisible(false);

        var2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var2.setForeground(new java.awt.Color(255, 255, 255));
        var2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var2.setText("x1");
        jPanel1.add(var2);
        var2.setBounds(190, 200, 30, 30);
        var2.setVisible(false);

        op5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op5.setForeground(new java.awt.Color(255, 255, 255));
        op5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op5.setText("+");
        jPanel1.add(op5);
        op5.setBounds(220, 200, 15, 30);

        e7.setBackground(new java.awt.Color(0, 0, 0));
        e7.setColumns(5);
        e7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e7.setForeground(new java.awt.Color(255, 255, 255));
        e7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e7.setText("0");
        e7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e7.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e7.setOpaque(false);
        e7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e7ActionPerformed(evt);
            }
        });
        e7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e7KeyTyped(evt);
            }
        });
        jPanel1.add(e7);
        e7.setBounds(240, 200, 70, 30);

        var6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var6.setForeground(new java.awt.Color(255, 255, 255));
        var6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var6.setText("x2");
        jPanel1.add(var6);
        var6.setBounds(310, 200, 30, 30);

        op6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op6.setForeground(new java.awt.Color(255, 255, 255));
        op6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op6.setText("+");
        jPanel1.add(op6);
        op6.setBounds(340, 200, 15, 30);

        e8.setBackground(new java.awt.Color(0, 0, 0));
        e8.setColumns(5);
        e8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e8.setForeground(new java.awt.Color(255, 255, 255));
        e8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e8.setText("0");
        e8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e8.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e8.setOpaque(false);
        e8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e8ActionPerformed(evt);
            }
        });
        e8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e8KeyTyped(evt);
            }
        });
        jPanel1.add(e8);
        e8.setBounds(360, 200, 70, 30);

        var10.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var10.setForeground(new java.awt.Color(255, 255, 255));
        var10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var10.setText("x3");
        jPanel1.add(var10);
        var10.setBounds(430, 200, 30, 30);

        op7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op7.setForeground(new java.awt.Color(255, 255, 255));
        op7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op7.setText("+");
        jPanel1.add(op7);
        op7.setBounds(460, 200, 15, 30);

        e9.setBackground(new java.awt.Color(0, 0, 0));
        e9.setColumns(5);
        e9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e9.setForeground(new java.awt.Color(255, 255, 255));
        e9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e9.setText("0");
        e9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e9.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e9.setOpaque(false);
        e9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e9KeyTyped(evt);
            }
        });
        jPanel1.add(e9);
        e9.setBounds(480, 200, 70, 30);

        var14.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var14.setForeground(new java.awt.Color(255, 255, 255));
        var14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var14.setText("x4");
        jPanel1.add(var14);
        var14.setBounds(550, 200, 30, 30);

        op8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op8.setForeground(new java.awt.Color(255, 255, 255));
        op8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op8.setText("=");
        jPanel1.add(op8);
        op8.setBounds(580, 200, 15, 30);

        e10.setBackground(new java.awt.Color(0, 0, 0));
        e10.setColumns(5);
        e10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e10.setForeground(new java.awt.Color(255, 255, 255));
        e10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e10.setText("0");
        e10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e10.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e10.setOpaque(false);
        e10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e10KeyTyped(evt);
            }
        });
        jPanel1.add(e10);
        e10.setBounds(600, 200, 70, 30);

        e11.setBackground(new java.awt.Color(0, 0, 0));
        e11.setColumns(5);
        e11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e11.setForeground(new java.awt.Color(255, 255, 255));
        e11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e11.setText("0");
        e11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e11.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e11.setOpaque(false);
        e11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e11ActionPerformed(evt);
            }
        });
        e11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e11KeyTyped(evt);
            }
        });
        jPanel1.add(e11);
        e11.setBounds(120, 250, 70, 30);

        var3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var3.setForeground(new java.awt.Color(255, 255, 255));
        var3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var3.setText("x1");
        jPanel1.add(var3);
        var3.setBounds(190, 250, 30, 30);

        op9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op9.setForeground(new java.awt.Color(255, 255, 255));
        op9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op9.setText("+");
        jPanel1.add(op9);
        op9.setBounds(220, 250, 15, 30);

        e12.setBackground(new java.awt.Color(0, 0, 0));
        e12.setColumns(5);
        e12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e12.setForeground(new java.awt.Color(255, 255, 255));
        e12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e12.setText("0");
        e12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e12.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e12.setOpaque(false);
        e12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e12KeyTyped(evt);
            }
        });
        jPanel1.add(e12);
        e12.setBounds(240, 250, 70, 30);

        var7.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var7.setForeground(new java.awt.Color(255, 255, 255));
        var7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var7.setText("x2");
        jPanel1.add(var7);
        var7.setBounds(310, 250, 30, 30);

        op10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op10.setForeground(new java.awt.Color(255, 255, 255));
        op10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op10.setText("+");
        jPanel1.add(op10);
        op10.setBounds(340, 250, 15, 30);

        e13.setBackground(new java.awt.Color(0, 0, 0));
        e13.setColumns(5);
        e13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e13.setForeground(new java.awt.Color(255, 255, 255));
        e13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e13.setText("0");
        e13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e13.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e13.setOpaque(false);
        e13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e13KeyTyped(evt);
            }
        });
        jPanel1.add(e13);
        e13.setBounds(360, 250, 70, 30);

        var11.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var11.setForeground(new java.awt.Color(255, 255, 255));
        var11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var11.setText("x3");
        jPanel1.add(var11);
        var11.setBounds(430, 250, 30, 30);

        op11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op11.setForeground(new java.awt.Color(255, 255, 255));
        op11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op11.setText("+");
        jPanel1.add(op11);
        op11.setBounds(460, 250, 15, 30);

        e14.setBackground(new java.awt.Color(0, 0, 0));
        e14.setColumns(5);
        e14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e14.setForeground(new java.awt.Color(255, 255, 255));
        e14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e14.setText("0");
        e14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e14.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e14.setOpaque(false);
        e14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e14KeyTyped(evt);
            }
        });
        jPanel1.add(e14);
        e14.setBounds(480, 250, 70, 30);

        var15.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var15.setForeground(new java.awt.Color(255, 255, 255));
        var15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var15.setText("x4");
        jPanel1.add(var15);
        var15.setBounds(550, 250, 30, 30);

        op12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op12.setForeground(new java.awt.Color(255, 255, 255));
        op12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op12.setText("=");
        jPanel1.add(op12);
        op12.setBounds(580, 250, 15, 30);

        e15.setBackground(new java.awt.Color(0, 0, 0));
        e15.setColumns(5);
        e15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e15.setForeground(new java.awt.Color(255, 255, 255));
        e15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e15.setText("0");
        e15.setToolTipText("");
        e15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e15.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e15.setOpaque(false);
        e15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e15KeyTyped(evt);
            }
        });
        jPanel1.add(e15);
        e15.setBounds(600, 250, 70, 30);

        e16.setBackground(new java.awt.Color(0, 0, 0));
        e16.setColumns(5);
        e16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e16.setForeground(new java.awt.Color(255, 255, 255));
        e16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e16.setText("0");
        e16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e16.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e16.setOpaque(false);
        e16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e16ActionPerformed(evt);
            }
        });
        e16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e16KeyTyped(evt);
            }
        });
        jPanel1.add(e16);
        e16.setBounds(120, 300, 70, 30);

        var4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var4.setForeground(new java.awt.Color(255, 255, 255));
        var4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var4.setText("x1");
        jPanel1.add(var4);
        var4.setBounds(190, 300, 30, 30);

        op13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op13.setForeground(new java.awt.Color(255, 255, 255));
        op13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op13.setText("+");
        jPanel1.add(op13);
        op13.setBounds(220, 300, 15, 30);

        e17.setBackground(new java.awt.Color(0, 0, 0));
        e17.setColumns(5);
        e17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e17.setForeground(new java.awt.Color(255, 255, 255));
        e17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e17.setText("0");
        e17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e17.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e17.setOpaque(false);
        e17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e17ActionPerformed(evt);
            }
        });
        e17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e17KeyTyped(evt);
            }
        });
        jPanel1.add(e17);
        e17.setBounds(240, 300, 70, 30);

        var8.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var8.setForeground(new java.awt.Color(255, 255, 255));
        var8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var8.setText("x2");
        jPanel1.add(var8);
        var8.setBounds(310, 300, 30, 30);

        op14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op14.setForeground(new java.awt.Color(255, 255, 255));
        op14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op14.setText("+");
        jPanel1.add(op14);
        op14.setBounds(340, 300, 15, 30);

        e18.setBackground(new java.awt.Color(0, 0, 0));
        e18.setColumns(5);
        e18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e18.setForeground(new java.awt.Color(255, 255, 255));
        e18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e18.setText("0");
        e18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e18.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e18.setOpaque(false);
        e18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e18KeyTyped(evt);
            }
        });
        jPanel1.add(e18);
        e18.setBounds(360, 300, 70, 30);

        var12.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var12.setForeground(new java.awt.Color(255, 255, 255));
        var12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var12.setText("x3");
        jPanel1.add(var12);
        var12.setBounds(430, 300, 30, 30);

        op15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op15.setForeground(new java.awt.Color(255, 255, 255));
        op15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op15.setText("+");
        jPanel1.add(op15);
        op15.setBounds(460, 300, 15, 30);

        e19.setBackground(new java.awt.Color(0, 0, 0));
        e19.setColumns(5);
        e19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e19.setForeground(new java.awt.Color(255, 255, 255));
        e19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e19.setText("0");
        e19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e19.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e19.setOpaque(false);
        e19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e19KeyTyped(evt);
            }
        });
        jPanel1.add(e19);
        e19.setBounds(480, 300, 70, 30);

        var16.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var16.setForeground(new java.awt.Color(255, 255, 255));
        var16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var16.setText("x4");
        jPanel1.add(var16);
        var16.setBounds(550, 300, 30, 30);

        op16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        op16.setForeground(new java.awt.Color(255, 255, 255));
        op16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op16.setText("=");
        jPanel1.add(op16);
        op16.setBounds(580, 300, 15, 30);

        e20.setBackground(new java.awt.Color(0, 0, 0));
        e20.setColumns(5);
        e20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e20.setForeground(new java.awt.Color(255, 255, 255));
        e20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e20.setText("0");
        e20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        e20.setMargin(new java.awt.Insets(0, 0, 2, 0));
        e20.setOpaque(false);
        e20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e20KeyTyped(evt);
            }
        });
        jPanel1.add(e20);
        e20.setBounds(600, 300, 70, 30);

        resumen.setEditable(false);
        resumen.setBackground(new java.awt.Color(5, 35, 59));
        resumen.setColumns(20);
        resumen.setForeground(new java.awt.Color(255, 255, 255));
        resumen.setRows(5);
        resumen.setCaretColor(new java.awt.Color(255, 255, 255));
        resumen.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(resumen);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 410, 740, 170);

        camb2.setBackground(new java.awt.Color(5, 35, 59));
        camb2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        camb2.setForeground(new java.awt.Color(255, 255, 255));
        camb2.setText("x1");
        camb2.setOpaque(false);
        camb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camb2ActionPerformed(evt);
            }
        });
        camb2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                camb2KeyPressed(evt);
            }
        });
        jPanel1.add(camb2);
        camb2.setBounds(40, 60, 30, 30);
        camb2.getAccessibleContext().setAccessibleName("");
        camb2.setVisible(false);

        var1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        var1.setForeground(new java.awt.Color(255, 255, 255));
        var1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var1.setText("x1");
        jPanel1.add(var1);
        var1.setBounds(190, 150, 30, 30);
        var1.setVisible(false);

        camb3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        camb3.setForeground(new java.awt.Color(255, 255, 255));
        camb3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        camb3.setText("; 2:");
        camb3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                camb3KeyPressed(evt);
            }
        });
        jPanel1.add(camb3);
        camb3.setBounds(70, 60, 30, 30);
        camb3.getAccessibleContext().setAccessibleName("");
        camb3.setVisible(false);

        camb4.setBackground(new java.awt.Color(5, 35, 59));
        camb4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        camb4.setForeground(new java.awt.Color(255, 255, 255));
        camb4.setText("x2");
        camb4.setOpaque(false);
        camb4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                camb4KeyPressed(evt);
            }
        });
        jPanel1.add(camb4);
        camb4.setBounds(100, 60, 30, 30);
        camb4.getAccessibleContext().setAccessibleName("");
        camb4.setVisible(false);

        camb5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        camb5.setForeground(new java.awt.Color(255, 255, 255));
        camb5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        camb5.setText("; 3:");
        jPanel1.add(camb5);
        camb5.setBounds(130, 60, 30, 30);
        camb5.getAccessibleContext().setAccessibleName("");
        camb5.setVisible(false);

        camb6.setBackground(new java.awt.Color(5, 35, 59));
        camb6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        camb6.setForeground(new java.awt.Color(255, 255, 255));
        camb6.setText("x3");
        camb6.setOpaque(false);
        camb6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                camb6KeyPressed(evt);
            }
        });
        jPanel1.add(camb6);
        camb6.setBounds(160, 60, 30, 30);
        camb6.getAccessibleContext().setAccessibleName("");
        camb6.setVisible(false);

        camb7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        camb7.setForeground(new java.awt.Color(255, 255, 255));
        camb7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        camb7.setText("; 4:");
        jPanel1.add(camb7);
        camb7.setBounds(190, 60, 30, 30);
        camb7.getAccessibleContext().setAccessibleName("");
        camb7.setVisible(false);

        camb8.setBackground(new java.awt.Color(5, 35, 59));
        camb8.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        camb8.setForeground(new java.awt.Color(255, 255, 255));
        camb8.setText("x4");
        camb8.setOpaque(false);
        camb8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                camb8KeyPressed(evt);
            }
        });
        jPanel1.add(camb8);
        camb8.setBounds(220, 60, 30, 30);
        camb8.getAccessibleContext().setAccessibleName("");
        camb8.setVisible(false);

        camb1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        camb1.setForeground(new java.awt.Color(255, 255, 255));
        camb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        camb1.setText("{1:");
        jPanel1.add(camb1);
        camb1.setBounds(10, 60, 30, 30);
        camb1.getAccessibleContext().setAccessibleName("");
        camb1.setVisible(false);

        jButton2.setText("Cambiar nombre variables");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setOpaque(false);
        jButton2.setVisible(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(60, 20, 160, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orig_665033.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e2ActionPerformed

    private void e3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e3ActionPerformed

    private void e6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e6ActionPerformed

    private void e7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e7ActionPerformed

    private void e8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e8ActionPerformed

    private void e11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e11ActionPerformed

    private void e16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e16ActionPerformed

    private void e17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            if (tamano.getItemAt(tamano.getSelectedIndex()) == "3x3") {
                if (e1.getText().equals("") || e2.getText().equals("") || e3.getText().equals("") || e5.getText().equals("")
                        || e6.getText().equals("") || e7.getText().equals("") || e8.getText().equals("") || e10.getText().equals("")
                        || e11.getText().equals("") || e12.getText().equals("") || e13.getText().equals("") || e15.getText().equals("")) {
                    throw new Exception("DEBE RELLENAR TODOS LOS CAMPOS CON NUMEROS");
                }

                String temp = "";
                String a = "";

                try {
                    NumberFormatException CrearMatriz3x3 = Resolver.CrearMatriz3x3(e1, e2, e3, e5, e6, e7, e8, e10, e11, e12, e13, e15);
                    if (CrearMatriz3x3 != null) {
                        throw new NumberFormatException();
                    }
                    temp += Resolver.imprimirMatriz3x3();
                    
                    temp += "\n Matriz creda \n ***********************************************************************************************************\n";
                    
                    
                    resumen.setText(temp);
                    a = Resolver.resolver3x3();

                    if (!Resolver.r) {
                        temp += a;
                        temp += "\n *****************************ecuacion solucion*************************\n";
                        if (Resolver.incompatible) {
                            temp += Resolver.get_fila1()[0]+ camb2.getText() + " + " + Resolver.get_fila1()[1] +camb4.getText();
                            temp += " + " + Resolver.get_fila2()[2]+ camb6.getText()  + "="+ Resolver.get_fila1()[3];
                            
                        }

                    } else {
                        temp += a;
                        temp += "*******************************RESULTADOS****************************\n";
                        temp += camb2.getText() + " = " + Resolver.get_fila1()[3] + "\n";
                        temp += camb4.getText() + " = " + Resolver.get_fila2()[3] + "\n";
                        temp += camb6.getText() + " = " + Resolver.get_fila3()[3];
                    }
                    resumen.setText(temp);
                } catch (NumberFormatException e) {

                }

            } else if (tamano.getItemAt(tamano.getSelectedIndex()) == "4x4") {
                if (e1.getText().equals("") || e2.getText().equals("") || e3.getText().equals("") || e4.getText().equals("") || e5.getText().equals("")
                        || e6.getText().equals("") || e7.getText().equals("") || e8.getText().equals("") || e9.getText().equals("") || e10.getText().equals("")
                        || e11.getText().equals("") || e12.getText().equals("") || e13.getText().equals("") || e14.getText().equals("") || e15.getText().equals("")
                        || e16.getText().equals("") || e17.getText().equals("") || e18.getText().equals("") || e19.getText().equals("") || e20.getText().equals("")) {
                    throw new Exception("DEBE RELLENAR TODOS LOS CAMPOS CON NUMEROS");
                }

                String temp = "";
                String a = "";

                try {
                    NumberFormatException CrearMatriz4x4 = Resolver.CrearMatriz4x4(e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20);
                    if (CrearMatriz4x4 != null) {
                        throw new NumberFormatException();
                    }
                    temp += Resolver.imprimirMatriz4x4();
                    temp += "\n Matriz creda \n ***********************************************************************************************************\n";

                    resumen.setText(temp);
                    a = Resolver.resolver4x4();

                    if (!Resolver.r) {
                        temp += a;
                        
                        if (Resolver.incompatible) {
                            temp += "\n *****************************ecuacion solucion*************************\n";
                            if(Resolver.getFila1()[0]!=0){
                                temp += Resolver.getFila1()[0]+ camb2.getText() + " + " + Resolver.getFila1()[1] +camb4.getText();
                                temp += " + " + Resolver.getFila1()[2]+ camb6.getText()  + " + " + Resolver.getFila1()[3]+ camb8.getText()
                                        + " = "+ Resolver.getFila1()[4];
                                temp+="\n";
                            }
                            if(Resolver.getFila2()[1]!=0){
                                temp += Resolver.getFila2()[0]+ camb2.getText() + " + " + Resolver.getFila2()[1] +camb4.getText();
                                temp += " + " + Resolver.getFila2()[2]+ camb6.getText()  + " + " + Resolver.getFila2()[3]+ camb8.getText()
                                        + " = "+ Resolver.getFila2()[4];
                                temp+="\n";
                            }
                            if(Resolver.getFila3()[2]!=0){
                                temp += Resolver.getFila3()[0]+ camb2.getText() + " + " + Resolver.getFila3()[1] +camb4.getText();
                                temp += " + " + Resolver.getFila3()[2]+ camb6.getText()  + " + " + Resolver.getFila3()[3]+ camb8.getText()
                                        + " = "+ Resolver.getFila3()[4];
                                temp+="\n";
                            }
                            if(Resolver.getFila4()[3]!=0){
                                temp += Resolver.getFila4()[0]+ camb2.getText() + " + " + Resolver.getFila4()[1] +camb4.getText();
                                temp += " + " + Resolver.getFila4()[2]+ camb6.getText()  + " + " + Resolver.getFila4()[3]+ camb8.getText()
                                        + " = "+ Resolver.getFila4()[4];
                                temp+="\n";
                            }
                            
                            
                        }
                    } else {
                        temp += a;
                        temp += "*******************************RESULTADOS****************************\n";
                        temp += camb2.getText() + " = " + Resolver.getFila1()[4] + "\n";
                        temp += camb4.getText() + " = " + Resolver.getFila2()[4] + "\n";
                        temp += camb6.getText() + " = " + Resolver.getFila3()[4] + "\n";
                        temp += camb8.getText() + " = " + Resolver.getFila4()[4];
                    }
                    resumen.setText(temp);
                } catch (NumberFormatException e) {

                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR EN CAMPOS DE TEXTO", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanoActionPerformed
        // TODO add your handling code here:
        if (tamano.getItemAt(tamano.getSelectedIndex()).equals("3x3")) {
            //detenemos el hilo que comprueba y cambia las variables
            if (comprobar.isAlive()) {
                comprobar.stop();
            }
            //reiniciar variables
            e1.setText("0");
            e2.setText("0");
            e3.setText("0");
            e4.setText("0");
            e5.setText("0");
            e6.setText("0");
            e7.setText("0");
            e8.setText("0");
            e9.setText("0");
            e10.setText("0");
            e11.setText("0");
            e12.setText("0");
            e13.setText("0");
            e14.setText("0");
            e15.setText("0");
            e16.setText("0");
            e17.setText("0");
            e18.setText("0");
            e19.setText("0");
            e20.setText("0");
            resumen.setText("");
            //se muestra el boton resolver
            jButton1.setVisible(true);
            //se muestra el boton que cambia las variables
            jButton2.setVisible(true);
            //campos que cambian las vaariables
            camb1.setVisible(false);
            camb2.setVisible(false);
            camb3.setVisible(false);
            camb4.setVisible(false);
            camb5.setVisible(false);
            camb6.setVisible(false);
            camb7.setVisible(false);
            camb8.setVisible(false);
            camb9.setVisible(false);
            camb9.setBounds(250, 60, 30, 30);
            //ecuacion1
            e1.setVisible(true);
            var1.setVisible(true);
            op1.setVisible(true);
            e2.setVisible(true);
            var5.setVisible(true);
            op2.setVisible(true);
            e3.setVisible(true);
            var9.setVisible(true);
            op3.setVisible(false);
            e4.setVisible(false);
            var13.setVisible(false);
            op4.setBounds(460, 150, 30, 30);
            e5.setBounds(480, 150, 70, 30);
            op4.setVisible(true);
            e5.setVisible(true);
            //ecuacion2
            e6.setVisible(true);
            var2.setVisible(true);
            op5.setVisible(true);
            e7.setVisible(true);
            var6.setVisible(true);
            op6.setVisible(true);
            e8.setVisible(true);
            var10.setVisible(true);
            op7.setVisible(false);
            e9.setVisible(false);
            var14.setVisible(false);
            op8.setBounds(460, 200, 15, 30);
            e10.setBounds(480, 200, 70, 30);
            op8.setVisible(true);
            e10.setVisible(true);
            //ecuacion3
            op12.setBounds(460, 250, 15, 30);
            e15.setBounds(480, 250, 70, 30);
            e11.setVisible(true);
            var3.setVisible(true);
            op9.setVisible(true);
            e12.setVisible(true);
            var7.setVisible(true);
            op10.setVisible(true);
            e13.setVisible(true);
            var11.setVisible(true);
            op11.setVisible(false);
            e14.setVisible(false);
            var15.setVisible(false);
            op12.setVisible(true);
            e15.setVisible(true);
            //ecuacion4
            op16.setBounds(460, 300, 15, 30);
            e20.setBounds(480, 300, 70, 30);
            e16.setVisible(false);
            var4.setVisible(false);
            op13.setVisible(false);
            e17.setVisible(false);
            var8.setVisible(false);
            op14.setVisible(false);
            e18.setVisible(false);
            var12.setVisible(false);
            op15.setVisible(false);
            e19.setVisible(false);
            var16.setVisible(false);
            op16.setVisible(false);
            e20.setVisible(false);

        } else if (tamano.getItemAt(tamano.getSelectedIndex()).equals("4x4")) {
            //detenemos el hilo que comprueba y cambia las variables
            if (comprobar.isAlive()) {
                comprobar.stop();
            }
            //se muestra el boton resolver
            jButton1.setVisible(true);
            //se muestra el boton que cambia las variables
            jButton2.setVisible(true);
            //campos que cambian las vaariables
            camb9.setBounds(250, 60, 30, 30);
            camb1.setVisible(false);
            camb2.setVisible(false);
            camb3.setVisible(false);
            camb4.setVisible(false);
            camb5.setVisible(false);
            camb6.setVisible(false);
            camb7.setVisible(false);
            camb8.setVisible(false);
            camb9.setVisible(false);
            //ecuacion1
            op4.setBounds(580, 150, 30, 30);
            e5.setBounds(600, 150, 70, 30);
            e1.setVisible(true);
            var1.setVisible(true);
            op1.setVisible(true);
            e2.setVisible(true);
            var5.setVisible(true);
            op2.setVisible(true);
            e3.setVisible(true);
            var9.setVisible(true);
            op3.setVisible(true);
            e4.setVisible(true);
            var13.setVisible(true);
            op4.setVisible(true);
            e5.setVisible(true);
            //ecuacion2
            e10.setBounds(600, 200, 70, 30);
            op8.setBounds(580, 200, 15, 30);
            e6.setVisible(true);
            var2.setVisible(true);
            op5.setVisible(true);
            e7.setVisible(true);
            var6.setVisible(true);
            op6.setVisible(true);
            e8.setVisible(true);
            var10.setVisible(true);
            op7.setVisible(true);
            e9.setVisible(true);
            var14.setVisible(true);
            op8.setVisible(true);
            e10.setVisible(true);
            //ecuacion3
            op12.setBounds(580, 250, 15, 30);
            e15.setBounds(600, 250, 70, 30);
            e11.setVisible(true);
            var4.setVisible(true);
            op9.setVisible(true);
            e12.setVisible(true);
            var8.setVisible(true);
            op10.setVisible(true);
            e13.setVisible(true);
            var12.setVisible(true);
            op11.setVisible(true);
            e14.setVisible(true);
            var16.setVisible(true);
            op12.setVisible(true);
            e15.setVisible(true);
            //ecuacion4
            op16.setBounds(580, 300, 15, 30);
            e20.setBounds(600, 300, 70, 30);
            e16.setVisible(true);
            var3.setVisible(true);
            op13.setVisible(true);
            e17.setVisible(true);
            var7.setVisible(true);
            op14.setVisible(true);
            e18.setVisible(true);
            var11.setVisible(true);
            op15.setVisible(true);
            e19.setVisible(true);
            var15.setVisible(true);
            op16.setVisible(true);
            e20.setVisible(true);

            //reiniciar variables
            e1.setText("0");
            e2.setText("0");
            e3.setText("0");
            e4.setText("0");
            e5.setText("0");
            e6.setText("0");
            e7.setText("0");
            e8.setText("0");
            e9.setText("0");
            e10.setText("0");
            e11.setText("0");
            e12.setText("0");
            e13.setText("0");
            e14.setText("0");
            e15.setText("0");
            e16.setText("0");
            e17.setText("0");
            e18.setText("0");
            e19.setText("0");
            e20.setText("0");
            resumen.setText("");
        } else {
            //detenemos el hilo que comprueba y cambia las variables
            if (comprobar.isAlive()) {
                comprobar.stop();
            }
            //reiniciar variables
            e1.setText("0");
            e2.setText("0");
            e3.setText("0");
            e4.setText("0");
            e5.setText("0");
            e6.setText("0");
            e7.setText("0");
            e8.setText("0");
            e9.setText("0");
            e10.setText("0");
            e11.setText("0");
            e12.setText("0");
            e13.setText("0");
            e14.setText("0");
            e15.setText("0");
            e16.setText("0");
            e17.setText("0");
            e18.setText("0");
            e19.setText("0");
            e20.setText("0");
            resumen.setText("");
            //se oculta el boton resolver
            jButton1.setVisible(false);
            //se oculta el boton que cambia las variables
            jButton2.setVisible(false);
            //ecuacion1
            e1.setVisible(false);
            var1.setVisible(false);
            op1.setVisible(false);
            e2.setVisible(false);
            var5.setVisible(false);
            op2.setVisible(false);
            e3.setVisible(false);
            var9.setVisible(false);
            op3.setVisible(false);
            e4.setVisible(false);
            var13.setVisible(false);
            op4.setVisible(false);
            e5.setVisible(false);
            //ecuacion2
            e6.setVisible(false);
            var2.setVisible(false);
            op5.setVisible(false);
            e7.setVisible(false);
            var6.setVisible(false);
            op6.setVisible(false);
            e8.setVisible(false);
            var10.setVisible(false);
            op7.setVisible(false);
            e9.setVisible(false);
            var14.setVisible(false);
            op8.setVisible(false);
            e10.setVisible(false);
            //ecuacion3
            e11.setVisible(false);
            var4.setVisible(false);
            op9.setVisible(false);
            e12.setVisible(false);
            var8.setVisible(false);
            op10.setVisible(false);
            e13.setVisible(false);
            var12.setVisible(false);
            op11.setVisible(false);
            e14.setVisible(false);
            var16.setVisible(false);
            op12.setVisible(false);
            e15.setVisible(false);
            //ecuacion4
            e16.setVisible(false);
            var3.setVisible(false);
            op13.setVisible(false);
            e17.setVisible(false);
            var7.setVisible(false);
            op14.setVisible(false);
            e18.setVisible(false);
            var11.setVisible(false);
            op15.setVisible(false);
            e19.setVisible(false);
            var15.setVisible(false);
            op16.setVisible(false);
            e20.setVisible(false);
        }


    }//GEN-LAST:event_tamanoActionPerformed

    private void camb3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_camb3KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_camb3KeyPressed

    private void camb2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_camb2KeyPressed
        // TODO add your handling code here:
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            var1.setText(camb2.getText());
            var2.setText(camb2.getText());
            var3.setText(camb2.getText());
            var4.setText(camb2.getText());
        }
    }//GEN-LAST:event_camb2KeyPressed

    private void camb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camb2ActionPerformed

    private void camb4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_camb4KeyPressed
        // TODO add your handling code here:
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            var5.setText(camb4.getText());
            var6.setText(camb4.getText());
            var7.setText(camb4.getText());
            var8.setText(camb4.getText());
        }
    }//GEN-LAST:event_camb4KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (!comprobar.isAlive()) {
            comprobar.start();
        }
        if (tamano.getItemAt(tamano.getSelectedIndex()).equals("3x3")) {
            camb1.setVisible(true);
            camb2.setVisible(true);
            camb3.setVisible(true);
            camb4.setVisible(true);
            camb5.setVisible(true);
            camb6.setVisible(true);
            camb9.setBounds(190, 60, 30, 30);
            camb9.setVisible(true);
        } else if (tamano.getItemAt(tamano.getSelectedIndex()).equals("4x4")) {

            camb1.setVisible(true);
            camb2.setVisible(true);
            camb3.setVisible(true);
            camb4.setVisible(true);
            camb5.setVisible(true);
            camb6.setVisible(true);
            camb7.setVisible(true);
            camb8.setVisible(true);
            camb9.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void e1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e1KeyTyped
        // TODO add your handling code here:
        evento(evt, e1);

    }//GEN-LAST:event_e1KeyTyped

    private void camb6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_camb6KeyPressed
        // TODO add your handling code here:
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            var9.setText(camb6.getText());
            var10.setText(camb6.getText());
            var11.setText(camb6.getText());
            var12.setText(camb6.getText());
        }
    }//GEN-LAST:event_camb6KeyPressed

    private void camb8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_camb8KeyPressed
        // TODO add your handling code here:
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            var13.setText(camb8.getText());
            var14.setText(camb8.getText());
            var15.setText(camb8.getText());
            var16.setText(camb8.getText());
        }
    }//GEN-LAST:event_camb8KeyPressed

    private void e6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e6KeyTyped
        // TODO add your handling code here:
        evento(evt, e6);
    }//GEN-LAST:event_e6KeyTyped

    private void e11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e11KeyTyped
        // TODO add your handling code here:
        evento(evt, e11);
    }//GEN-LAST:event_e11KeyTyped

    private void e16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e16KeyTyped
        // TODO add your handling code here:
        evento(evt, e16);
    }//GEN-LAST:event_e16KeyTyped

    private void e2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e2KeyTyped
        // TODO add your handling code here:
        evento(evt, e2);
    }//GEN-LAST:event_e2KeyTyped

    private void e7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e7KeyTyped
        // TODO add your handling code here:
        evento(evt, e7);
    }//GEN-LAST:event_e7KeyTyped

    private void e12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e12KeyTyped
        // TODO add your handling code here:
        evento(evt, e12);
    }//GEN-LAST:event_e12KeyTyped

    private void e17KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e17KeyTyped
        // TODO add your handling code here:
        evento(evt, e17);
    }//GEN-LAST:event_e17KeyTyped

    private void e3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e3KeyTyped
        // TODO add your handling code here:
        evento(evt, e3);
    }//GEN-LAST:event_e3KeyTyped

    private void e8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e8KeyTyped
        // TODO add your handling code here:
        evento(evt, e8);
    }//GEN-LAST:event_e8KeyTyped

    private void e13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e13KeyTyped
        // TODO add your handling code here:
        evento(evt, e13);
    }//GEN-LAST:event_e13KeyTyped

    private void e18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e18KeyTyped
        // TODO add your handling code here:
        evento(evt, e18);
    }//GEN-LAST:event_e18KeyTyped

    private void e4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e4KeyTyped
        // TODO add your handling code here:
        evento(evt, e4);
    }//GEN-LAST:event_e4KeyTyped

    private void e9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e9KeyTyped
        // TODO add your handling code here:
        evento(evt, e9);
    }//GEN-LAST:event_e9KeyTyped

    private void e14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e14KeyTyped
        // TODO add your handling code here:
        evento(evt, e14);
    }//GEN-LAST:event_e14KeyTyped

    private void e19KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e19KeyTyped
        // TODO add your handling code here:
        evento(evt, e19);
    }//GEN-LAST:event_e19KeyTyped

    private void e5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e5KeyTyped
        // TODO add your handling code here:
        evento(evt, e5);
    }//GEN-LAST:event_e5KeyTyped

    private void e10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e10KeyTyped
        // TODO add your handling code here:
        evento(evt, e10);
    }//GEN-LAST:event_e10KeyTyped

    private void e15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e15KeyTyped
        // TODO add your handling code here:
        evento(evt, e15);
    }//GEN-LAST:event_e15KeyTyped

    private void e20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e20KeyTyped
        // TODO add your handling code here:
        evento(evt, e20);
    }//GEN-LAST:event_e20KeyTyped

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel camb1;
    private javax.swing.JTextField camb2;
    private javax.swing.JLabel camb3;
    private javax.swing.JTextField camb4;
    private javax.swing.JLabel camb5;
    private javax.swing.JTextField camb6;
    private javax.swing.JLabel camb7;
    private javax.swing.JTextField camb8;
    private javax.swing.JLabel camb9;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField e10;
    private javax.swing.JTextField e11;
    private javax.swing.JTextField e12;
    private javax.swing.JTextField e13;
    private javax.swing.JTextField e14;
    private javax.swing.JTextField e15;
    private javax.swing.JTextField e16;
    private javax.swing.JTextField e17;
    private javax.swing.JTextField e18;
    private javax.swing.JTextField e19;
    private javax.swing.JTextField e2;
    private javax.swing.JTextField e20;
    private javax.swing.JTextField e3;
    private javax.swing.JTextField e4;
    private javax.swing.JTextField e5;
    private javax.swing.JTextField e6;
    private javax.swing.JTextField e7;
    private javax.swing.JTextField e8;
    private javax.swing.JTextField e9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel op1;
    private javax.swing.JLabel op10;
    private javax.swing.JLabel op11;
    private javax.swing.JLabel op12;
    private javax.swing.JLabel op13;
    private javax.swing.JLabel op14;
    private javax.swing.JLabel op15;
    private javax.swing.JLabel op16;
    private javax.swing.JLabel op2;
    private javax.swing.JLabel op3;
    private javax.swing.JLabel op4;
    private javax.swing.JLabel op5;
    private javax.swing.JLabel op6;
    private javax.swing.JLabel op7;
    private javax.swing.JLabel op8;
    private javax.swing.JLabel op9;
    private javax.swing.JTextArea resumen;
    private javax.swing.JComboBox<String> tamano;
    private javax.swing.JLabel var1;
    private javax.swing.JLabel var10;
    private javax.swing.JLabel var11;
    private javax.swing.JLabel var12;
    private javax.swing.JLabel var13;
    private javax.swing.JLabel var14;
    private javax.swing.JLabel var15;
    private javax.swing.JLabel var16;
    private javax.swing.JLabel var2;
    private javax.swing.JLabel var3;
    private javax.swing.JLabel var4;
    private javax.swing.JLabel var5;
    private javax.swing.JLabel var6;
    private javax.swing.JLabel var7;
    private javax.swing.JLabel var8;
    private javax.swing.JLabel var9;
    // End of variables declaration//GEN-END:variables
}
